// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/fleet": {
            "get": {
                "description": "Returns all sessions grouped by flavor, excluding lost sessions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "Get fleet state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies": {
            "get": {
                "description": "Returns all token policies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "List policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Policy"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new token policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Create policy",
                "parameters": [
                    {
                        "description": "Policy definition",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.Policy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/{id}": {
            "put": {
                "description": "Updates an existing token policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Update policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Policy definition",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Policy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a token policy",
                "tags": [
                    "policies"
                ],
                "summary": "Delete policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/policy": {
            "get": {
                "description": "Returns the most specific policy for a given flavor/session scope. Lookup order: session \u003e flavor \u003e org",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Get effective policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent flavor",
                        "name": "flavor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Policy"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions/{id}": {
            "get": {
                "description": "Returns session metadata (including effective policy thresholds) and all events in chronological order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get session detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stream": {
            "get": {
                "description": "WebSocket connection for real-time fleet state updates. Upgrades HTTP to WebSocket.",
                "tags": [
                    "stream"
                ],
                "summary": "Real-time fleet stream",
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.PolicyRequest": {
            "type": "object",
            "properties": {
                "block_at_pct": {
                    "type": "integer"
                },
                "degrade_at_pct": {
                    "type": "integer"
                },
                "degrade_to": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "scope_value": {
                    "type": "string"
                },
                "token_limit": {
                    "type": "integer"
                },
                "warn_at_pct": {
                    "type": "integer"
                }
            }
        },
        "handlers.SessionResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.Event"
                    }
                },
                "session": {
                    "$ref": "#/definitions/store.Session"
                }
            }
        },
        "store.Event": {
            "type": "object",
            "properties": {
                "event_type": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "has_content": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "latency_ms": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "tokens_input": {
                    "type": "integer"
                },
                "tokens_output": {
                    "type": "integer"
                },
                "tokens_total": {
                    "type": "integer"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "store.Policy": {
            "type": "object",
            "properties": {
                "block_at_pct": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "degrade_at_pct": {
                    "type": "integer"
                },
                "degrade_to": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "scope_value": {
                    "type": "string"
                },
                "token_limit": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "warn_at_pct": {
                    "type": "integer"
                }
            }
        },
        "store.Session": {
            "type": "object",
            "properties": {
                "agent_type": {
                    "type": "string"
                },
                "block_at_pct": {
                    "type": "integer"
                },
                "degrade_at_pct": {
                    "type": "integer"
                },
                "degrade_to": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "framework": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "policy_token_limit": {
                    "description": "Active policy thresholds (nullable).\nPopulated by GetSession via effective policy lookup.\nNull if no policy applies at any scope.",
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "token_limit": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                },
                "warn_at_pct": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Flightdeck Query API",
	Description:      "Fleet visibility, session history, and control plane for AI agent fleets",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
