// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/analytics": {
            "get": {
                "description": "Flexible GROUP BY analytics endpoint. Returns time series data grouped by dimension.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Query analytics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric: tokens, sessions, latency_avg, policy_events (default: tokens)",
                        "name": "metric",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Dimension: flavor, model, framework, host, agent_type, team (default: flavor)",
                        "name": "group_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Time range: 7d, 30d, 90d, custom (default: 30d)",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time ISO 8601 (required when range=custom)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time ISO 8601 (required when range=custom)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Granularity: hour, day, week (default: day)",
                        "name": "granularity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to specific flavor",
                        "name": "filter_flavor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to specific model",
                        "name": "filter_model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to specific agent_type",
                        "name": "filter_agent_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.AnalyticsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/directives": {
            "post": {
                "description": "Issues a shutdown directive to a single agent session or all sessions of a flavor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directives"
                ],
                "summary": "Create directive",
                "parameters": [
                    {
                        "description": "Directive definition",
                        "name": "directive",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DirectiveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.Directive"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/events/{id}/content": {
            "get": {
                "description": "Returns prompt capture content for an event. Returns 404 when the event does not exist or capture was not enabled.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get event content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.EventContent"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/fleet": {
            "get": {
                "description": "Returns sessions grouped by flavor, excluding lost sessions. Supports pagination via limit/offset on sessions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "Get fleet state",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max sessions to return (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset into sessions list (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by agent type: 'developer', 'production', or empty for all",
                        "name": "agent_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.FleetResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies": {
            "get": {
                "description": "Returns all token policies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "List policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Policy"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new token policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Create policy",
                "parameters": [
                    {
                        "description": "Policy definition",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.Policy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/{id}": {
            "put": {
                "description": "Updates an existing token policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Update policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Policy definition",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Policy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a token policy",
                "tags": [
                    "policies"
                ],
                "summary": "Delete policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/policy": {
            "get": {
                "description": "Returns the most specific policy for a given flavor/session scope. Lookup order: session \u003e flavor \u003e org",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Get effective policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent flavor",
                        "name": "flavor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Policy"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/search": {
            "get": {
                "description": "Searches agents, sessions, and events by partial match. Returns up to 5 results per group.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Cross-entity search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (min 1, max 200 characters)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.SearchResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions/{id}": {
            "get": {
                "description": "Returns session metadata (including effective policy thresholds) and all events in chronological order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get session detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stream": {
            "get": {
                "description": "WebSocket connection for real-time fleet state updates. Upgrades HTTP to WebSocket.",
                "tags": [
                    "stream"
                ],
                "summary": "Real-time fleet stream",
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DirectiveRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "grace_period_ms": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.FleetResponse": {
            "type": "object",
            "properties": {
                "flavors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.FlavorSummary"
                    }
                },
                "total_session_count": {
                    "type": "integer"
                }
            }
        },
        "handlers.PolicyRequest": {
            "type": "object",
            "properties": {
                "block_at_pct": {
                    "type": "integer"
                },
                "degrade_at_pct": {
                    "type": "integer"
                },
                "degrade_to": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "scope_value": {
                    "type": "string"
                },
                "token_limit": {
                    "type": "integer"
                },
                "warn_at_pct": {
                    "type": "integer"
                }
            }
        },
        "handlers.SessionResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.Event"
                    }
                },
                "session": {
                    "$ref": "#/definitions/store.Session"
                }
            }
        },
        "store.AnalyticsResponse": {
            "type": "object",
            "properties": {
                "granularity": {
                    "type": "string"
                },
                "group_by": {
                    "type": "string"
                },
                "metric": {
                    "type": "string"
                },
                "range": {
                    "type": "string"
                },
                "series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.AnalyticsSeries"
                    }
                },
                "totals": {
                    "$ref": "#/definitions/store.AnalyticsTotals"
                }
            }
        },
        "store.AnalyticsSeries": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DataPoint"
                    }
                },
                "dimension": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "store.AnalyticsTotals": {
            "type": "object",
            "properties": {
                "grand_total": {
                    "type": "number"
                },
                "period_change_pct": {
                    "type": "number"
                }
            }
        },
        "store.DataPoint": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "store.Directive": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "degrade_to": {
                    "type": "string"
                },
                "delivered_at": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "grace_period_ms": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "issued_at": {
                    "type": "string"
                },
                "issued_by": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "store.Event": {
            "type": "object",
            "properties": {
                "event_type": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "has_content": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "latency_ms": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "tokens_input": {
                    "type": "integer"
                },
                "tokens_output": {
                    "type": "integer"
                },
                "tokens_total": {
                    "type": "integer"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "store.EventContent": {
            "type": "object",
            "properties": {
                "captured_at": {
                    "type": "string"
                },
                "event_id": {
                    "type": "string"
                },
                "messages": {},
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "response": {},
                "session_id": {
                    "type": "string"
                },
                "system_prompt": {
                    "type": "string"
                },
                "tools": {}
            }
        },
        "store.FlavorSummary": {
            "type": "object",
            "properties": {
                "active_count": {
                    "type": "integer"
                },
                "agent_type": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "session_count": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.Session"
                    }
                },
                "tokens_used_total": {
                    "type": "integer"
                }
            }
        },
        "store.Policy": {
            "type": "object",
            "properties": {
                "block_at_pct": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "degrade_at_pct": {
                    "type": "integer"
                },
                "degrade_to": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "scope_value": {
                    "type": "string"
                },
                "token_limit": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "warn_at_pct": {
                    "type": "integer"
                }
            }
        },
        "store.SearchResultAgent": {
            "type": "object",
            "properties": {
                "agent_type": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                }
            }
        },
        "store.SearchResultEvent": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "store.SearchResultSession": {
            "type": "object",
            "properties": {
                "flavor": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "store.SearchResults": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.SearchResultAgent"
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.SearchResultEvent"
                    }
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.SearchResultSession"
                    }
                }
            }
        },
        "store.Session": {
            "type": "object",
            "properties": {
                "agent_type": {
                    "type": "string"
                },
                "block_at_pct": {
                    "type": "integer"
                },
                "degrade_at_pct": {
                    "type": "integer"
                },
                "degrade_to": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "framework": {
                    "type": "string"
                },
                "has_pending_directive": {
                    "description": "HasPendingDirective is true when an undelivered shutdown directive exists.",
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "policy_token_limit": {
                    "description": "Active policy thresholds (nullable).\nPopulated by GetSession via effective policy lookup.\nNull if no policy applies at any scope.",
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "token_limit": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                },
                "warn_at_pct": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Flightdeck Query API",
	Description:      "Fleet visibility, session history, and control plane for AI agent fleets",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
