package store

import (
	"context"
	"fmt"
	"time"
)

// AgentSummaryParams selects the window + bucketing for
// “GET /v1/agents/{id}/summary“. The handler validates every
// field's vocabulary before reaching the store; the store trusts
// its caller for that layer.
type AgentSummaryParams struct {
	// AgentID is the UUID the handler already validated against
	// uuidRE. Empty is rejected at the handler layer; the store
	// never sees an empty value in normal flow but emits a
	// well-formed query either way.
	AgentID string
	// Period is one of ``1h``, ``24h``, ``7d``, ``30d``. Drives
	// the lower bound of the window (``now - period``). The
	// handler rejects unknown values.
	Period string
	// Bucket is one of ``hour``, ``day``, ``week`` and feeds
	// ``date_trunc``. Default is derived from Period at the
	// handler layer.
	Bucket string
}

// AgentSummaryTotals carries the across-the-window aggregates the
// per-agent landing page renders in its summary tiles. “Errors“
// counts events of type “llm_error“ only — policy events
// (policy_block / policy_warn / policy_degrade / policy_mcp_*)
// are enforcement decisions, not failures, and live on a separate
// dashboard surface. “Sessions“ is distinct session_id across
// events in the window (every session that had activity counts,
// regardless of when it started — operators read "sessions" as
// "agents that were active here", not "sessions started here").
type AgentSummaryTotals struct {
	Tokens       int64   `json:"tokens"`
	Errors       int64   `json:"errors"`
	Sessions     int64   `json:"sessions"`
	CostUSD      float64 `json:"cost_usd"`
	LatencyP50MS int64   `json:"latency_p50_ms"`
	LatencyP95MS int64   `json:"latency_p95_ms"`
}

// AgentSummarySeriesPoint is one per-bucket row in the time
// series the chart renders. p50 is intentionally absent here —
// charts plot p95 (the operator-actionable headline number) and
// the summary tile carries p50 for context.
type AgentSummarySeriesPoint struct {
	// TS is the bucket's start, truncated to the requested
	// granularity (``date_trunc(bucket, occurred_at)``). Serialised
	// as RFC 3339 / ISO 8601 by Go's default JSON encoder.
	TS           time.Time `json:"ts"`
	Tokens       int64     `json:"tokens"`
	Errors       int64     `json:"errors"`
	Sessions     int64     `json:"sessions"`
	CostUSD      float64   `json:"cost_usd"`
	LatencyP95MS int64     `json:"latency_p95_ms"`
}

// AgentSummaryResponse is the full “GET /v1/agents/{id}/summary“
// payload. “Series“ is always non-nil (empty slice for agents
// with no activity in the window) so the dashboard's chart code
// never has to distinguish “null“ from “[]“.
type AgentSummaryResponse struct {
	AgentID string                    `json:"agent_id"`
	Period  string                    `json:"period"`
	Bucket  string                    `json:"bucket"`
	Totals  AgentSummaryTotals        `json:"totals"`
	Series  []AgentSummarySeriesPoint `json:"series"`
}

// agentSummaryPeriodToDuration maps the four supported period
// vocabulary values to their lower-bound offsets. Centralised so
// the handler's validation list and the store's window
// computation can never drift.
func agentSummaryPeriodToDuration(period string) (time.Duration, bool) {
	switch period {
	case "1h":
		return time.Hour, true
	case "24h":
		return 24 * time.Hour, true
	case "7d":
		return 7 * 24 * time.Hour, true
	case "30d":
		return 30 * 24 * time.Hour, true
	}
	return 0, false
}

// AgentSummary runs the totals + series queries for one agent
// over the requested period. The two queries share the same
// FROM / WHERE shape; running them sequentially keeps each plan
// simple and avoids forcing the planner to fold totals into the
// per-bucket aggregate (which would either need a window function
// or a CTE that some operators would have to re-explain on call).
//
// Latency percentiles use “event_type = 'post_call'“ only —
// matching the existing analytics convention for “latency_p50“
// / “latency_p95“ in analytics.go. Errors count events of type
// “llm_error“; policy events are excluded.
func (s *Store) AgentSummary(
	ctx context.Context, params AgentSummaryParams,
) (*AgentSummaryResponse, error) {
	dur, ok := agentSummaryPeriodToDuration(params.Period)
	if !ok {
		return nil, fmt.Errorf("invalid period: %s", params.Period)
	}
	switch params.Bucket {
	case "hour", "day", "week":
	default:
		return nil, fmt.Errorf("invalid bucket: %s", params.Bucket)
	}

	end := time.Now().UTC()
	start := end.Add(-dur)

	costExpr := BuildCostAggregateSQL("e.model")

	// Totals query. FILTER (WHERE ...) lets one pass over the
	// joined rows produce each metric's filtered aggregate
	// without splitting the query into N round-trips.
	//
	// The cost expression is a bare ``COALESCE(SUM(...), 0)``
	// generated by BuildCostAggregateSQL — it does not carry an
	// explicit FILTER on event_type because attaching FILTER to
	// the outer COALESCE is illegal SQL and the inner SUM is
	// already implicitly scoped: only ``post_call`` rows populate
	// the token columns, every other event_type leaves
	// tokens_input / tokens_output / tokens_cache_* NULL so the
	// per-row contribution evaluates to 0 / NULL and SUM ignores
	// it. The numeric result is identical to an explicitly
	// FILTERed expression.
	//
	// COUNT(DISTINCT session_id) is unfiltered: an agent's
	// "sessions in the window" is every session that emitted at
	// least one event regardless of event type — matching the
	// operator-facing definition recorded in
	// AgentSummaryTotals's docstring.
	totalsSQL := `
		SELECT
			COALESCE(SUM(e.tokens_total)
				FILTER (WHERE e.event_type = 'post_call'), 0) AS tokens,
			COUNT(*) FILTER (WHERE e.event_type = 'llm_error') AS errors,
			COUNT(DISTINCT e.session_id) AS sessions,
			COALESCE(` + costExpr + `, 0) AS cost_usd,
			COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY e.latency_ms)
				FILTER (WHERE e.event_type = 'post_call'), 0) AS p50,
			COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY e.latency_ms)
				FILTER (WHERE e.event_type = 'post_call'), 0) AS p95
		FROM events e
		JOIN sessions s ON e.session_id = s.session_id
		WHERE s.agent_id = $1::uuid
		  AND e.occurred_at >= $2
		  AND e.occurred_at < $3
	`

	resp := &AgentSummaryResponse{
		AgentID: params.AgentID,
		Period:  params.Period,
		Bucket:  params.Bucket,
		Series:  []AgentSummarySeriesPoint{},
	}

	var totals AgentSummaryTotals
	var costUSD, p50, p95 float64
	if err := s.pool.QueryRow(ctx, totalsSQL,
		params.AgentID, start, end,
	).Scan(
		&totals.Tokens,
		&totals.Errors,
		&totals.Sessions,
		&costUSD,
		&p50,
		&p95,
	); err != nil {
		return nil, fmt.Errorf("agent summary totals: %w", err)
	}
	totals.CostUSD = costUSD
	totals.LatencyP50MS = int64(p50)
	totals.LatencyP95MS = int64(p95)
	resp.Totals = totals

	// Series query. The bucket name is validated against the
	// hour/day/week whitelist above so the date_trunc literal is
	// safe to interpolate. Buckets with no rows simply don't
	// appear; the chart code handles the gap rather than the
	// query padding with zeros.
	//
	//nolint:gosec // params.Bucket from the hour/day/week whitelist
	// validated five lines above; never reaches this Sprintf with
	// an unsanctioned value.
	seriesSQL := fmt.Sprintf(`
		SELECT
			date_trunc('%s', e.occurred_at) AS bucket,
			COALESCE(SUM(e.tokens_total)
				FILTER (WHERE e.event_type = 'post_call'), 0) AS tokens,
			COUNT(*) FILTER (WHERE e.event_type = 'llm_error') AS errors,
			COUNT(DISTINCT e.session_id) AS sessions,
			COALESCE(%s, 0) AS cost_usd,
			COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY e.latency_ms)
				FILTER (WHERE e.event_type = 'post_call'), 0) AS p95
		FROM events e
		JOIN sessions s ON e.session_id = s.session_id
		WHERE s.agent_id = $1::uuid
		  AND e.occurred_at >= $2
		  AND e.occurred_at < $3
		GROUP BY bucket
		ORDER BY bucket
	`, params.Bucket, costExpr)

	rows, err := s.pool.Query(ctx, seriesSQL,
		params.AgentID, start, end)
	if err != nil {
		return nil, fmt.Errorf("agent summary series: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var pt AgentSummarySeriesPoint
		var pCost, p95 float64
		if err := rows.Scan(
			&pt.TS,
			&pt.Tokens,
			&pt.Errors,
			&pt.Sessions,
			&pCost,
			&p95,
		); err != nil {
			return nil, fmt.Errorf("agent summary series scan: %w", err)
		}
		pt.CostUSD = pCost
		pt.LatencyP95MS = int64(p95)
		resp.Series = append(resp.Series, pt)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("agent summary series rows: %w", err)
	}

	return resp, nil
}
