/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        "bg-elevated": "var(--bg-elevated)",
        "surface-hover": "var(--surface-hover)",
        border: "var(--border)",
        "border-subtle": "var(--border-subtle)",
        "border-strong": "var(--border-strong)",
        text: "var(--text)",
        "text-muted": "var(--text-muted)",
        "text-secondary": "var(--text-secondary)",
        "text-disabled": "var(--text-disabled)",
        primary: "var(--primary)",
        "primary-glow": "var(--primary-glow)",
        accent: "var(--accent)",
        "accent-glow": "var(--accent-glow)",
        "status-active": "var(--status-active)",
        "status-idle": "var(--status-idle)",
        "status-stale": "var(--status-stale)",
        "status-lost": "var(--status-lost)",
        "status-closed": "var(--status-closed)",
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
        "color-warn": "var(--color-warn)",
        "color-degrade": "var(--color-degrade)",
        "color-block": "var(--color-block)",
      },
    },
  },
  plugins: [],
};
